### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by KongsNutz** [nesrak1/AddressablesTools#2]
[catalog.json](https://github.com/nesrak1/AddressablesTools/files/13802448/catalog.json)
This file does not work with the tool, I've managed to use the tool on other games catalog files but this one gives an exception error.

**Comment by nesrak1** [comment]
Are you using release? This works fine for me when I use the latest code in the repo. I can't make a release right now, but it should be easy enough to build the project.

**Comment by KongsNutz** [comment]
> Are you using release? This works fine for me when I use the latest code in the repo. I can't make a release right now, but it should be easy enough to build the project.
Yeh I'm using the latest precompiled version you have... I'd have to build my own if you can't do one for me atm. (Not sure where to start tbh)

**Comment by KongsNutz** [comment]
Thank you, managed to build it myself and it patched the crc perfectly :)

**Comment by KongsNutz** [comment]
Closed
